### PR TITLE
More scripts for fermilab workshop in August

### PR DESCRIPTION
**Pull request by alexandertuna**
Hi @bartosik-hep @spagangriso,

Here's a draft PR which adds more pylcio scripts for the tutorial. The `dumpers/` directory includes a handful of scripts for printing event information (mcparticles, sim hits, digi hits, reco objects, LC relations, cellid decoding) at each stage of the tutorial. The `analysis/pylcio/` directory includes more analysis scripts to give more examples, and also an example with pandas/matplotlib. The scripts are simple `pyLCIO` scripts, i.e. without drivers, to lower the barrier of entry for new people. 

There's also a `grid/` directory, which has an example of submitting grid jobs on the new osg/chicago host (`ap23`), though I'm not sure if it belongs here.

Todo for Alex:

- [x] Rerun `black` on all scripts
- [x] <del>Remove `grid/` ?</del>
- [x] Check for conflict with https://github.com/MuonColliderSoft/MuC-Tutorial/pull/4
- [x] Rerun with 2.9.X container when available

### CODE REVIEW

**Comment by bartosik-hep** [comment]
I think that `grid/` scripts can be kept if they are going to be used in the tutorial. 
I would wait for confirmation that everything works under the `2.9.X` container before merging.

**Comment by alexandertuna** [comment]
Thanks @bartosik-hep . I agree, let's keep this as a PR until testing with `2.9.1`.

**Comment by alexandertuna** [comment]
Hi @bartosik-hep . I tested these scripts with the 2.9.1 container (below) and they seem to work fine. I think they're ready for review and/or merging as you prefer.

```
/cvmfs/unpacked.cern.ch/registry.hub.docker.com/infnpd/mucoll-minimal:2.9.1-almalinux9
```

**Comment by spagangriso** [comment]
@bartosik-hep , we tested this and since this PR is just adding files I'd go ahead and merge it since we're getting close to tutorial day.

**Pull request merged**
